---
title: "Análisis exploratorio de los datos"
---

# Importar librerías

En esta sección, se importan las librerías necesarias para el análisis exploratorio de los datos de las acciones de Bitcoin. Se utilizarán herramientas como Pandas y Numpy para el manejo de los datos, Plotly para la visualización, y algunos módulos de statsmodels para el análisis de series de tiempo y pruebas estadísticas.

```{python}
import pandas as pd
import numpy as np

import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

from sklearn.impute import KNNImputer

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.stattools import acf, adfuller
from statsmodels.stats.diagnostic import acorr_ljungbox

import warnings
warnings.filterwarnings("ignore")
```

# Importar datos

A continuación, se realiza la importación de los datos históricos de Bitcoin desde una fuente externa. Estos datos contienen información relevante sobre las acciones, que se utilizará en el análisis para identificar tendencias, patrones y comportamiento de la serie temporal.

``` {python}
btc = pd.read_csv('https://raw.githubusercontent.com/lihkir/Data/refs/heads/main/Bitcoin%20Historical%20Data.csv')

btc.head()
```

# Exploración de los datos

En esta sección, se observa la forma general del DataFrame para conocer el número de registros y columnas.

``` {python}
btc.shape
```

Descripción inicial del DataFrame, mostrando las columnas, tipos de datos y valores nulos presentes:

``` {python}
btc.info()
```

Para realizar el análisis, es necesario convertir las columnas numéricas de tipo string a float y la columna Date a un formato de fecha. A continuación, se aplica la conversión de datos y se ajusta el formato de los volúmenes.

``` {python}
btc[['Price', 'Open', 'High', 'Low']] = btc[['Price', 'Open', 'High', 'Low']].replace(',', '', regex=True).astype(float)
btc['Change %'] = btc['Change %'].str.replace('%', '').astype(float)

btc['Date'] = pd.to_datetime(btc['Date'], format='%m/%d/%Y')

def convert_volume(vol):
    if isinstance(vol, str):
        if 'K' in vol:
            return float(vol.replace('K', '').replace(',', '')) * 1_000
        elif 'M' in vol:
            return float(vol.replace('M', '').replace(',', '')) * 1_000_000
        elif 'B' in vol:
            return float(vol.replace('B', '').replace(',', '')) * 1_000_000_000
        else:
            return float(vol.replace(',', ''))
    else:
        return vol

btc['Vol.'] = btc['Vol.'].apply(convert_volume)

btc.head()
```

Luego de las conversiones, se revisa la estructura actual del DataFrame para confirmar que los tipos de datos sean correctos y que se hayan eliminado los símbolos y comas.

``` {python}
btc.info()
```

``` {python}
btc.describe()
```

El resumen estadístico revela que el precio promedio de Bitcoin ha sido de aproximadamente 10,812.28 dólares, con un precio de apertura promedio cercano de 10,798.90 dólares. A lo largo del tiempo, los precios diarios más altos han promediado 11,067.45 dólares, mientras que los precios más bajos se han situado en 10,511.89 dólares, indicando una volatilidad diaria moderada. El volumen promedio de transacciones ha sido de 12.38 millones, mostrando un mercado activo, aunque con periodos de bajo volumen mínimo de 80 unidades. El cambio porcentual promedio ha sido positivo, de 0.42% por día, pero con episodios de alta volatilidad que incluyen caídas de hasta -57.21%. Además, los precios han sido significativamente bajos en el primer cuartil, con un valor de 226.70 dólares, lo que indica que durante un cuarto del tiempo analizado, el precio de Bitcoin se mantuvo muy por debajo de los niveles actuales.

# Datos faltantes

El análisis de los datos faltantes en el conjunto de datos de Bitcoin muestra que la columna Volumen presenta valores nulos, que representan un pequeño porcentaje del total de registros. Para manejar estos datos faltantes, se ha implementado una imputación utilizando el algoritmo KNNImputer con 5 vecinos. Este enfoque permite estimar los valores faltantes en función de los patrones observados en los datos circundantes, lo cual es efectivo para mantener la coherencia y calidad de la información antes de proceder con el análisis de series de tiempo.

``` {python}
missing_values = btc.isnull().sum()
missing_percentage = round((missing_values / len(btc)) * 100, 4)
missing_percentage
```

La columna `Vol.` presenta un 0.12% de datos faltantes, lo cual es un porcentaje bajo pero significativo para los análisis.

Para completar los valores faltantes en la columna de Volumen, se emplea el algoritmo de imputación KNNImputer, que utiliza la información de los vecinos más cercanos para predecir los valores faltantes.

``` {python}
imputer = KNNImputer(n_neighbors = 5)

btc[['Vol.']] = imputer.fit_transform(btc[['Vol.']])

btc.head()
```

# Visualización de precio y volumen tradeado

``` {python}
#| output: false
fig = go.Figure(
    data = [
        go.Candlestick(
            x = btc['Date'],
            open = btc['Open'],
            high = btc['High'],
            low = btc['Low'],
            close = btc['Price'],
            name = 'Precio Bitcoin'
        )
    ]
)

fig.update_layout(
    title='Gráfico de Velas de Bitcoin',
    xaxis_title='Fecha',
    yaxis_title='Precio (USD)',
    hovermode='x',
    margin={'b': 0, 'r': 30, 'l': 30, 't': 40},
    xaxis={'gridcolor': '#222', 'tickfont': {'color': 'white'}},
    yaxis={'gridcolor': '#222', 'tickfont': {'color': 'white'}},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis_rangeslider_visible=False,
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/candlestick_price.html')
```

``` {=html}
<iframe
    src = 'graphs/candlestick_price.html'
    width = '730'
    height = '400'
    title = 'Candlestick de la serie de tiempo del precio'
>
</iframe>
```

En el gráfico de velas del Bitcoin se puede observar la evolución del precio de esta criptomoneda a lo largo del tiempo, abarcando desde sus primeros días hasta el año 2024. El gráfico revela períodos de alta volatilidad, con importantes picos en los años 2017-2018 y 2020-2022, en los cuales se registraron máximos históricos seguidos de caídas rápidas. Estos movimientos bruscos sugieren una naturaleza especulativa y altamente volátil en el mercado de Bitcoin. En el periodo más reciente (2023-2024), se evidencia un nuevo máximo cercano a los 70,000 USD, acompañado de correcciones pronunciadas, lo que indica una posible consolidación con fluctuaciones significativas. 

``` {python}
#| output: false
fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x = btc['Date'],
        y = btc['Vol.'],
        name = 'Volumen',
        histfunc = 'sum'
    )
)

fig.update_layout(
    title='Histograma de Volumen Tradeado Diario',
    xaxis_title='Fecha',
    yaxis_title='Volumen tradeado',
    bargap=0.1,
    margin={'b': 0, 'r': 30, 'l': 30, 't': 40},
    xaxis={'gridcolor': '#222', 'tickfont': {'color': 'white'}},
    yaxis={'gridcolor': '#222', 'tickfont': {'color': 'white'}},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/histogram_vol.html')
```

``` {=html}
<iframe
    src = 'graphs/histogram_vol.html'
    width = '730'
    height = '400'
    title = 'Histograma del volumen de tradeado'
>
</iframe>
```

En el histograma del volumen tradeado diario de Bitcoin se puede observar un patrón particular en la actividad de trading a lo largo del tiempo. La gráfica muestra un aumento abrupto y masivo del volumen tradeado en un periodo específico, alrededor del año 2022. Esto sugiere que durante este período hubo un incremento significativo en la cantidad de Bitcoin intercambiado, superando los 60 mil millones de unidades. Antes de este aumento, el volumen diario se mantuvo relativamente bajo y estable, lo que indica que la mayoría de la actividad de trading se concentró en los años más recientes. Este comportamiento puede estar relacionado con un mayor interés de inversores, la adopción generalizada de Bitcoin o la participación de grandes actores del mercado, provocando así picos de actividad inusuales. La presencia de este único pico elevado en la gráfica sugiere un cambio estructural en el mercado, lo cual es crucial para tener en cuenta en los análisis posteriores y en la modelización de la serie temporal.

# Visualización semanal, mensual y anual del precio del bitcoin

``` {python}
btc_c = btc.copy()
btc_c.set_index('Date', inplace = True)

weekly_btc = btc_c.resample('W').mean()
monthly_btc = btc_c.resample('M').mean()
yearly_btc = btc_c.resample('Y').mean()
```

``` {python}
#| output: false
fig_ts = make_subplots(
    rows=3, cols=1, 
    shared_xaxes=True, 
    subplot_titles=(
        'Precio Promedio Semanal',
        'Precio Promedio Mensual',
        'Precio Promedio Anual'
    )
)

fig_ts.add_trace(
    go.Scatter(
        x=weekly_btc.index, 
        y=weekly_btc['Price'], 
        mode='lines+markers', 
        name='Precio Semanal'
    ), 
    row=1, col=1
)

fig_ts.add_trace(
    go.Scatter(
        x=monthly_btc.index, 
        y=monthly_btc['Price'], 
        mode='lines+markers', 
        name='Precio Mensual'
    ), 
    row=2, col=1
)

fig_ts.add_trace(
    go.Scatter(
        x=yearly_btc.index, 
        y=yearly_btc['Price'], 
        mode='lines+markers', 
        name='Precio Anual'
    ), 
    row=3, col=1
)

fig_ts.update_layout(
    title='Series de Tiempo Agrupadas (Semana, Mes, Año)',
    xaxis_title='Fecha',
    yaxis_title='Precio (USD)',
    margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis2=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis2=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis3=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis3=dict(gridcolor='#222', tickfont=dict(color='white')),
    hovermode = 'x unified',
    showlegend = False
)

fig_ts.show()
```

``` {python}
#| echo: false
fig_ts.write_html('graphs/ts_variety.html')
```

``` {=html}
<iframe
    src = 'graphs/ts_variety.html'
    width = '700'
    height = '800'
    title = 'Series de Tiempo Agrupadas (Semana, Mes, Año)'
>
</iframe>
```

En las series de tiempo agrupadas por semana, mes y año, se observa la evolución del precio promedio de Bitcoin con diferentes niveles de agregación. El gráfico semanal revela fluctuaciones cortas y alta volatilidad, mientras que el mensual suaviza estos movimientos, destacando picos en 2017-2018 y 2020-2022, reflejando ciclos de auge y caída. Por último, el gráfico anual muestra un crecimiento sostenido desde 2017, con un notable aumento en 2021 y una estabilización posterior hasta un nuevo máximo en 2024. Esta combinación permite analizar tanto la volatilidad a corto plazo como las tendencias a largo plazo.

``` {python}
btc_c['Week'] = btc_c.index.to_series().dt.isocalendar().week
btc_c['Month'] = btc_c.index.to_series().dt.month
btc_c['Year'] = btc_c.index.to_series().dt.year
```

``` {python}
#| output: false
def get_box(df: pd.DataFrame, X: str, Y: str, TITLE: str):
    fig = px.box(
        df,
        x = X,
        y = Y,
        title = TITLE
    )

    fig.update_layout(
        margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
        plot_bgcolor='rgba(0, 0, 0, 0.0)',
        paper_bgcolor='rgba(0, 0, 0, 0.0)',
        font_color="white",
        hoverlabel=dict(
            bgcolor="#222"
        ),
        xaxis=dict(gridcolor='#222', tickfont=dict(color='white'), title = 'Semana'),
        yaxis=dict(gridcolor='#222', tickfont=dict(color='white'), title = 'Precio')
    )

    return fig

fig_box_w = get_box(btc_c, 'Week', 'Price', 'Distribución semanal')
fig_box_m = get_box(btc_c, 'Month', 'Price', 'Distribución mensual')
fig_box_y = get_box(btc_c, 'Year', 'Price', 'Distribución anual')

fig_box_w.show()
fig_box_m.show()
fig_box_y.show()
```

``` {python}
#| echo: false
fig_box_w.write_html('graphs/box_variety_w.html')
fig_box_m.write_html('graphs/box_variety_m.html')
fig_box_y.write_html('graphs/box_variety_y.html')
```

``` {=html}
<iframe
    src = 'graphs/box_variety_w.html'
    width = '730'
    height = '400'
    title = 'Series de Tiempo Agrupadas (Semana, Mes, Año)'
>
</iframe>
```

``` {=html}
<iframe
    src = 'graphs/box_variety_m.html'
    width = '730'
    height = '400'
    title = 'Series de Tiempo Agrupadas (Semana, Mes, Año)'
>
</iframe>
```

``` {=html}
<iframe
    src = 'graphs/box_variety_y.html'
    width = '730'
    height = '400'
    title = 'Series de Tiempo Agrupadas (Semana, Mes, Año)'
>
</iframe>
```

En los gráficos de distribución semanal, mensual y anual del precio de Bitcoin, se observa la variabilidad y dispersión del precio en diferentes escalas de tiempo. En la distribución semanal, los boxplots reflejan una amplia variabilidad, con picos notables en algunas semanas donde el precio superó los 60,000 USD, lo que sugiere fluctuaciones significativas en cortos periodos. En la distribución mensual, los rangos son más amplios, y se observan outliers frecuentes que destacan eventos extremos en cada mes, especialmente en los primeros y últimos meses del año. Por último, la distribución anual muestra una tendencia de expansión del rango de precios a medida que avanza el tiempo, con un crecimiento constante y variabilidad creciente desde 2016, alcanzando picos de precio más elevados en 2021 y 2024.

# Validación de estacionariedad de la serie de tiempo

``` {python}
#| output: false
lag_acf = acf(btc_c['Price'], nlags=2000)

fig = go.Figure()

fig.add_trace(go.Bar(
    x=list(range(len(lag_acf))),
    y=lag_acf,
    marker_color='blue'
))

fig.update_layout(
    title='Autocorrelación',
    xaxis_title='Lags',
    yaxis_title='Autocorrelación',
    margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis=dict(gridcolor='#222', tickfont=dict(color='white'))
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/acf_1.html')
```

``` {=html}
<iframe
    src = 'graphs/acf_1.html'
    width = '730'
    height = '400'
    title = 'ACF de las diferencias estacionales'
>
</iframe>
```

En el gráfico de autocorrelación, se representa la correlación de la serie temporal del precio de Bitcoin consigo misma en diferentes retardos (lags). La autocorrelación inicial es cercana a 1, lo cual indica que los valores consecutivos del precio están altamente correlacionados, es decir, existe una fuerte dependencia entre observaciones adyacentes. A medida que aumenta el número de retardos, la autocorrelación disminuye gradualmente hasta acercarse a cero, lo que sugiere que las observaciones distantes en el tiempo tienen poca o ninguna relación entre sí.

Esta tendencia de decaimiento lento es una señal de que la serie no es estacionaria, ya que la autocorrelación no converge rápidamente hacia cero. La no estacionariedad implica que hay patrones como tendencias o ciclos que persisten en el tiempo, lo cual es importante tener en cuenta para modelar adecuadamente esta serie y elegir métodos de transformación que permitan hacerla estacionaria para aplicar modelos que asumen esta propiedad.

## Prueba de estacionariedad de Ljung-Box

``` {python}
result = acorr_ljungbox(btc_c['Price'], lags=[200, 500, 1000, 2000], return_df=True)

if (result['lb_pvalue'] < 0.05).any():
    print("La serie no es estacionaria (rechazamos la hipótesis nula para algunos lags).")
else:
    print("La serie es estacionaria (no se rechaza la hipótesis nula para los lags evaluados).")

result
```

## Prueba de estacionariedad de Dickey Fuller

``` {python}
result = adfuller(btc_c['Price'])

print(f'Estadístico de prueba: {result[0]}')
print(f'Valor p: {result[1]}\n')

if result[1] < 0.05:
    print("La serie es estacionaria (rechazamos la hipótesis nula).")
else:
    print("La serie no es estacionaria (no se rechaza la hipótesis nula).")
```

## Transformaciones para obtener una serie estacionaria

Para obtener una serie estacionaria y facilitar el análisis y modelado de los precios de Bitcoin, se procederá a realizar una transformación basada en la diferenciación. La serie original ha mostrado indicios de no ser estacionaria, con un decaimiento lento en la autocorrelación, lo cual sugiere la presencia de tendencia. Por esta razón, se aplicará la diferenciación, que consiste en restar a cada valor su valor previo, con el objetivo de eliminar tendencias y estabilizar la media de la serie. Posteriormente, se evaluará la estacionariedad de la serie diferenciada mediante la prueba de Dickey-Fuller Aumentada (ADF), observando si el valor p es menor a 0.05, lo que indicaría que la serie ya es estacionaria.

``` {python}
btc_d = btc_c.copy()
btc_d['Price'] = btc_c['Price'].diff()

btc_d
```

``` {python}
result_diff = adfuller(btc_d['Price'].dropna())
print(f'Estadístico de prueba: {result_diff[0]}')
print(f'Valor p: {result_diff[1]}\n')

if result_diff[1] < 0.05:
    print("La serie diferenciada es estacionaria (rechazamos la hipótesis nula).")
else:
    print("La serie diferenciada no es estacionaria (no se rechaza la hipótesis nula).")
```

# Comportamiento por agrupaciones de la serie de tiempo

Para explorar más a fondo el comportamiento de la serie diferenciada, se realizará un análisis por períodos, agrupando los datos a nivel diario, semanal y mensual para calcular la media y la desviación estándar de los precios en cada intervalo. Esto permitirá identificar patrones de variabilidad en diferentes escalas temporales. También se calcularán medias y desviaciones estándar móviles para ventanas de 7, 30 y 90 días, lo que ayudará a observar cómo evolucionan el promedio y la dispersión de los precios a lo largo del tiempo.

``` {python}
weekly = btc_d['Price'].resample('W').agg(['mean', 'std'])
daily = btc_d['Price'].resample('D').agg(['mean', 'std'])
monthly = btc_d['Price'].resample('M').agg(['mean', 'std'])
```

``` {python}
btc_d['mu_7'] = btc_d['Price'].rolling(window = 7).mean()
btc_d['std_7'] = btc_d['Price'].rolling(window = 7).std()

btc_d['mu_30'] = btc_d['Price'].rolling(window = 30).mean()
btc_d['std_30'] = btc_d['Price'].rolling(window = 30).std()

btc_d['mu_90'] = btc_d['Price'].rolling(window = 90).mean()
btc_d['std_90'] = btc_d['Price'].rolling(window = 90).std()

btc_d
```

``` {python}
#| output: false
def get_hist(df: pd.DataFrame, diff_: int, title: str):
    fig = px.histogram(
        df['Price'].diff(diff_).dropna(),
        nbins = 30,
        title = title
    )

    fig.update_layout(
        margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
        plot_bgcolor='rgba(0, 0, 0, 0.0)',
        paper_bgcolor='rgba(0, 0, 0, 0.0)',
        font_color="white",
        hoverlabel=dict(
            bgcolor="#222"
        ),
        xaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
        yaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
        showlegend = False
    )

    return fig

fig_7 = get_hist(btc_d, 7, 'Distribución con lag = 7')
fig_30 = get_hist(btc_d, 30, 'Distribución con lag = 30')
fig_90 = get_hist(btc_d, 90, 'Distribución con lag = 90')

fig_7.show()
fig_30.show()
fig_90.show()
```

``` {python}
#| echo: false
fig_7.write_html('graphs/hist_7.html')
fig_30.write_html('graphs/hist_30.html')
fig_90.write_html('graphs/hist_90.html')
```

``` {=html}
<iframe
    src = 'graphs/hist_7.html'
    width = '730'
    height = '400'
    title = 'Distribución con lag = 7'
>
</iframe>
```

``` {=html}
<iframe
    src = 'graphs/hist_30.html'
    width = '730'
    height = '400'
    title = 'Distribución con lag = 30'
>
</iframe>
```

``` {=html}
<iframe
    src = 'graphs/hist_90.html'
    width = '730'
    height = '400'
    title = 'Distribución con lag = 90'
>
</iframe>
```

En los histogramas de las distribuciones con diferentes retardos (lags) de 7, 30 y 90 días, se puede observar la variabilidad de los precios diferenciados del Bitcoin a lo largo del tiempo. En los tres gráficos, se nota una clara concentración de los valores alrededor de cero, indicando que la mayoría de las diferencias en los precios son relativamente pequeñas en cada lag evaluado.

Sin embargo, a medida que aumenta el lag de 7 a 30 y luego a 90 días, se aprecia un aumento gradual en la dispersión de los datos, lo cual se refleja en colas más extendidas en los histogramas. Este comportamiento indica que, conforme se incrementa el período de comparación, las diferencias de precio tienden a ser más amplias, sugiriendo una mayor variabilidad en el largo plazo.

# Medias móviles y tendencia

``` {python}
#| output: false
btc_d = btc_d.fillna(0)

MA2 = btc_d['Price'].rolling(window = 2).mean()
TwoXMA2 = MA2.rolling(window=2).mean()

MA4 = btc_d['Price'].rolling(window = 4).mean()
TwoXMA4 = MA4.rolling(window=2).mean()

MA3 = btc_d['Price'].rolling(window = 3).mean()
ThreeXMA3 = MA3.rolling(window=3).mean()

fig = make_subplots(
    rows=3, cols=1, 
    shared_xaxes=True, 
    subplot_titles=("2 day MA & 2X2 day MA", "4 day MA & 2X4 day MA", "3 day MA & 3X3 day MA")
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=btc_d['Price'].iloc[:45], 
        mode='lines', 
        name='Close Price', 
        line=dict(color='#9B7EBD')
    ), 
    row=1, col=1
)
fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=MA2.iloc[:45], 
        mode='lines', 
        name='2 day MA', 
        line=dict(color='#7AB2D3', dash='dash')
    ), 
    row=1, col=1
)
fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=TwoXMA2.iloc[:45], 
        mode='lines', 
        name='2X2 day MA', 
        line=dict(color='#CBD2A4', dash='dash')
    ), 
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=btc_d['Price'].iloc[:45], 
        mode='lines', 
        name='Close Price', 
        showlegend=False, 
        line=dict(color='#9B7EBD')
    ), 
    row=2, col=1
)
fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=MA4.iloc[:45], 
        mode='lines', 
        name='4 day MA', 
        line=dict(color='#7AB2D3', dash='dash')
    ), 
    row=2, col=1
)
fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=TwoXMA4.iloc[:45], 
        mode='lines', 
        name='2X4 day MA', 
        line=dict(color='#CBD2A4', dash='dash')
    ), 
    row=2, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=btc_d['Price'].iloc[:45], 
        mode='lines', 
        name='Close Price', 
        showlegend=False, 
        line=dict(color='#9B7EBD')
    ), 
    row=3, col=1
)
fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=MA3.iloc[:45], 
        mode='lines', 
        name='3 day MA', 
        line=dict(color='#7AB2D3', dash='dash')
    ), 
    row=3, col=1
)
fig.add_trace(
    go.Scatter(
        x=btc_d.index[:45], 
        y=ThreeXMA3.iloc[:45], 
        mode='lines', 
        name='3X3 day MA', 
        line=dict(color='#CBD2A4', dash='dash')
    ), 
    row=3, col=1
)

fig.update_layout(
    title='',
    margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis=dict(
        gridcolor='#222', 
        tickfont=dict(color='white')
    ),
    yaxis=dict(
        gridcolor='#222', 
        tickfont=dict(color='white')
    ),
    xaxis2=dict(
        gridcolor='#222', 
        tickfont=dict(color='white')
    ),
    yaxis2=dict(
        gridcolor='#222', 
        tickfont=dict(color='white')
    ),
    xaxis3=dict(
        gridcolor='#222', 
        tickfont=dict(color='white')
    ),
    yaxis3=dict(
        gridcolor='#222', 
        tickfont=dict(color='white')
    ),
    hovermode='x unified',
    showlegend=False
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/media_movil.html')
```

``` {=html}
<iframe
    src = 'graphs/media_movil.html'
    width = '730'
    height = '800'
    title = 'Distribución con lag = 7'
>
</iframe>
```

Los gráficos muestran la evolución de los precios diferenciados de Bitcoin utilizando medias móviles (2, 3 y 4 días) y sus versiones suavizadas (2X y 3X). Las medias móviles siguen de cerca las fluctuaciones a corto plazo, mientras que las medias dobles suavizan las curvas, destacando tendencias más claras y menos influenciadas por variaciones bruscas. Las curvas suavizadas permiten identificar patrones subyacentes y direcciones generales, eliminando parte del ruido presente en los datos diarios. Esto facilita la visualización de la evolución de los precios en diferentes escalas temporales.

La descomposición de la serie de tiempo se realiza para identificar y separar sus componentes clave: tendencia, estacionalidad y residuales, lo que facilita el análisis y el modelado.

``` {python}
#| output: false
decomposition = seasonal_decompose(
    btc_d['Price'], 
    model='additive', 
    period=180
)

fig = make_subplots(
    rows=4, cols=1, 
    shared_xaxes=True, 
    subplot_titles=("Observado", "Tendencia", "Estacionalidad", "Residual")
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index, 
        y=btc_d['Price'], 
        mode='lines', 
        name='Observado', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index, 
        y=decomposition.trend, 
        mode='lines', 
        name='Tendencia', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=2, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index, 
        y=decomposition.seasonal, 
        mode='lines', 
        name='Estacionalidad', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=3, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_d.index, 
        y=decomposition.resid, 
        mode='lines', 
        name='Residual', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=4, col=1
)

fig.update_layout(
    title_text="Descomposición Estacional de la Serie de Tiempo", 
    showlegend=False,
    margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis2=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis2=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis3=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis3=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis4=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis4=dict(gridcolor='#222', tickfont=dict(color='white')),
    hovermode = 'x unified',
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/descomposition.html')
```

``` {=html}
<iframe
    src = 'graphs/descomposition.html'
    width = '730'
    height = '800'
    title = 'Distribución con lag = 7'
>
</iframe>
```

La serie observada muestra una mayor volatilidad en los últimos años. La tendencia revela un comportamiento de largo plazo, destacando caídas y recuperaciones. La estacionalidad presenta patrones cíclicos repetitivos, indicando un componente periódico constante en la serie. Finalmente, los residuales capturan las variaciones no explicadas, mostrando un aumento de la fluctuación aleatoria en el periodo reciente. Esta separación es crucial para comprender mejor la dinámica del precio del Bitcoin.

Ahora, se ajusta el precio diferenciado de Bitcoin restando la media móvil doble de 4 días (TwoXMA4) para eliminar el componente de tendencia y suavizar las fluctuaciones de corto plazo. Este ajuste ayuda a centrarse en los cambios más significativos y reduce la influencia de la variabilidad corta. Al realizar esta transformación, se obtiene una serie que resalta las desviaciones del comportamiento promedio reciente, facilitando la identificación de patrones o anomalías.

``` {python}
btc_ma = btc_d.copy()

btc_ma['Price_adj'] = btc_ma['Price'] - TwoXMA4
btc_ma = btc_ma.fillna(0)
```

``` {python}
#| output: false
decomposition = seasonal_decompose(
    btc_ma['Price_adj'], 
    model='additive', 
    period=180
)

fig = make_subplots(
    rows=4, cols=1, 
    shared_xaxes=True, 
    subplot_titles=("Observado", "Tendencia", "Estacionalidad", "Residual")
)

fig.add_trace(
    go.Scatter(
        x=btc_ma.index, 
        y=btc_ma['Price_adj'], 
        mode='lines', 
        name='Observado', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_ma.index, 
        y=decomposition.trend, 
        mode='lines', 
        name='Tendencia', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=2, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_ma.index, 
        y=decomposition.seasonal, 
        mode='lines', 
        name='Estacionalidad', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=3, col=1
)

fig.add_trace(
    go.Scatter(
        x=btc_ma.index, 
        y=decomposition.resid, 
        mode='lines', 
        name='Residual', 
        line=dict(color='#9B7EBD', width=2)
    ),
    row=4, col=1
)

fig.update_layout(
    title_text="Descomposición Estacional de la Serie de Tiempo", 
    showlegend=False,
    margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis2=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis2=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis3=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis3=dict(gridcolor='#222', tickfont=dict(color='white')),
    xaxis4=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis4=dict(gridcolor='#222', tickfont=dict(color='white')),
    hovermode = 'x unified',
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/descomposition_2.html')
```

``` {=html}
<iframe
    src = 'graphs/descomposition_2.html'
    width = '730'
    height = '800'
    title = 'Distribución con lag = 7'
>
</iframe>
```

Se observa que la tendencia se ha aplanado considerablemente, lo que indica que las oscilaciones de corto plazo fueron removidas. La estacionalidad se mantiene, evidenciando ciclos recurrentes y patrones que persisten en la serie. Los residuales ahora capturan mejor las fluctuaciones no explicadas, lo cual puede indicar la presencia de variabilidad no sistemática o ruido en los datos. En conjunto, esta transformación permite aislar los patrones relevantes y eliminar las influencias de corto plazo, proporcionando una base más clara para el análisis de la serie de tiempo.

Ahora, verificaremos si nuestra serie de tiempo se mantiene siendo estacionaria o no.

## Prueba de estacionariedad de Ljung-Box

``` {python}
result = acorr_ljungbox(btc_ma['Price_adj'], lags=[24, 100, 200], return_df=True)

if (result['lb_pvalue'] < 0.05).any():
    print("La serie no es estacionaria (rechazamos la hipótesis nula para algunos lags).")
else:
    print("La serie es estacionaria (no se rechaza la hipótesis nula para los lags evaluados).")

result
```

## Prueba de estacionariedad de Dickey Fuller

``` {python}
result = adfuller(btc_ma['Price_adj'])

print(f'Estadístico de prueba: {result[0]}')
print(f'Valor p: {result[1]}\n')

if result[1] < 0.05:
    print("La serie es estacionaria (rechazamos la hipótesis nula).")
else:
    print("La serie no es estacionaria (no se rechaza la hipótesis nula).")
```

``` {python}
#| output: false
lag_acf = acf(btc_ma['Price_adj'], nlags=100)

fig = go.Figure()

fig.add_trace(go.Bar(
    x=list(range(len(lag_acf))),
    y=lag_acf,
    marker_color='blue'
))

fig.update_layout(
    title='Autocorrelación',
    xaxis_title='Lags',
    yaxis_title='Autocorrelación',
    margin={'b': 0, 'r': 30, 'l': 30, 't': 80},
    plot_bgcolor='rgba(0, 0, 0, 0.0)',
    paper_bgcolor='rgba(0, 0, 0, 0.0)',
    font_color="white",
    hoverlabel=dict(
        bgcolor="#222"
    ),
    xaxis=dict(gridcolor='#222', tickfont=dict(color='white')),
    yaxis=dict(gridcolor='#222', tickfont=dict(color='white'))
)

fig.show()
```

``` {python}
#| echo: false
fig.write_html('graphs/acf_2.html')
```

``` {=html}
<iframe
    src = 'graphs/acf_2.html'
    width = '730'
    height = '400'
    title = 'ACF de las diferencias estacionales'
>
</iframe>
```

# Retorno acumulado diario y volatilidad 

``` {python}
btc['R_j'] = btc['Price'].pct_change()
btc['A_t'] = btc['R_j'].cumsum()

def calc_volt(btc: pd.DataFrame, window: int):
    return btc['R_j'].rolling(window = window).std()

ws = [7, 14, 21, 28]
for w in ws:
    btc[f'σ_{w}'] = calc_volt(btc, w)

btc
```

``` {python}
btc.to_csv('data/btc_models.csv', index = False)
```